### ISSUE TITLE
Suspected windows build issue - failed test verifyPrettyPrinter(org.openrtb.common.json.AbstractJsonTranslatorTest) on Windows but OK on Linux

### ISSUE THREAD

**Issue by chompi** [chompi/openrtb2x#8]
_Original author: Simon.Re...@gmail.com (May 08, 2011 13:20:34)_

<b>What steps will reproduce the problem?</b>
1. Clone code on Windows XP or Windows 7 (I've tested on both)
2. mvn package

<b>What is the expected output? What do you see instead?</b>
## Test set: org.openrtb.common.json.AbstractJsonTranslatorTest

Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec <<< FAILURE!
verifyPrettyPrinter(org.openrtb.common.json.AbstractJsonTranslatorTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: pretty printer didn't return the expected results expected:<{[
  "object" : {
    "value" : "subtype-value"
  },
  "long" : 1234,
  "string" : "parent-value"]
}> but was:<{[
  "object" : {
    "value" : "subtype-value"
  },
  "long" : 1234,
  "string" : "parent-value"
]
}>
    at org.junit.Assert.assertEquals(Assert.java:123)
    at org.openrtb.common.json.AbstractJsonTranslatorTest.verifyPrettyPrinter(AbstractJsonTranslatorTest.java:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

<b>What version of the product are you using? On what operating system?</b>
I have the tip (version 110) checked out on Windows XP and Windows 7

<b>Please provide any additional information below.</b>
The reason I think this is a Windows issue is that it works fine on my CentOS box (5.5). The other clue is that on my CentOS box the default encoding is UTF-8
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
...whereas on windows its Cp1252
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources,i.e. build is platform dependent!

The offending code: 
    public void verifyPrettyPrinter() throws IOException {
        test.usePrettyPrinter();
        assertEquals("pretty printer didn't return the expected results", PRETTY_VALUE, test.toJSON(PARENT));

I've attached the logs

_Original issue: http://code.google.com/p/openrtb/issues/detail?id=8_

**Comment by chompi** [comment]
_From willard....@gtempaccount.com on May 08, 2011 13:26:51_
We may need to explicitly set the encoding to UTF-8

**Comment by chompi** [comment]
_From rajesh.k...@gmail.com on July 14, 2011 07:26:00_
I am observing the same issue on a Windows Vista machine, should I provide the platform encoding as part of pom.xml to fix this issue?

**Comment by chompi** [comment]
_From rajesh.k...@gmail.com on July 14, 2011 07:43:06_
I added the following properties for the build to use UTF-8 in the root pom.xml, but the changes didn't make a difference though.

  <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>${project.build.sourceEncoding}</project.reporting.outputEncoding>
        <file.encoding>${project.build.sourceEncoding}</file.encoding>
  </properties>

**Comment by chompi** [comment]
_From Simon.Re...@gmail.com on August 07, 2011 14:57:05_
So I figured it out. Its a line separator issue. On windows the line separator is \r\n, but on linux its just \n. 
I'll apply a patch in the next 24 hours.

**Comment by chompi** [comment]
_From Simon.Re...@gmail.com on August 08, 2011 02:20:36_
The JSON generator (Jackson) has a prettyprint option that is tested in  verifyPrettyPrinter(org.openrtb.common.json.AbstractJsonTranslatorTest)
However, by default the generator uses class org.codehaus.jackson.impl.DefaultPrettyPrinter.Lf2SpacesIndenter
and the line separators that it generates are specific to the OS and therefore we need to check the line separators used in order to generate the correct PRETTY_VALUE to compare against

**Comment by chompi** [comment]
_From rajesh.k...@gmail.com on August 08, 2011 08:52:57_
Works fine, with the new changes.
